# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test with Keycloak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
    
    - name: Start Keycloak using dasniko/testcontainers-keycloak
      run: |
        docker run -d \
          --name keycloak \
          -p 9990:8080 \
          -e KEYCLOAK_ADMIN=admin \
          -e KEYCLOAK_ADMIN_PASSWORD=admin \
          dasniko/testcontainers-keycloak:latest
    
    - name: Wait for Keycloak
      run: |
        echo "Waiting for Keycloak to start..."

        timeout 120 bash -c 'until docker exec keycloak curl -f http://localhost:8080/health/ready 2>/dev/null; do 
          echo "Waiting for Keycloak health check... ($(date))"
          sleep 10
        done'
        
        timeout 60 bash -c 'until curl -f http://localhost:9990/health/ready 2>/dev/null; do 
          echo "Waiting for host access... ($(date))"
          sleep 5
        done'
        
        echo "Keycloak is ready!"
    
    - name: Create test realm
      run: |
        ACCESS_TOKEN=$(curl -s -X POST http://localhost:9990/realms/master/protocol/openid-connect/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=admin" \
          -d "password=admin" \
          -d "grant_type=password" \
          -d "client_id=admin-cli" | jq -r '.access_token')
        
        # Создаем realm
        curl -X POST http://localhost:9990/admin/realms \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "realm": "idm",
            "enabled": true,
            "displayName": "Test Realm"
          }'
        
        timeout 30 bash -c 'until curl -f http://localhost:9990/realms/idm/protocol/openid-connect/certs; do 
          sleep 2
        done'
        
        echo "Test realm created!"
    
    - name: Run tests
      run: go test -v ./inner/...
    
    - name: Debug on failure
      if: failure()
      run: |
        echo "=== Container Status ==="
        docker ps -a
        
        echo "=== Keycloak Logs ==="
        docker logs keycloak
        
        echo "=== Test connection ==="
        curl -v http://localhost:9990/health/ready || echo "Health endpoint failed"
        curl -v http://localhost:9990/realms/idm/protocol/openid-connect/certs || echo "JWKS failed"
    
    - name: Cleanup
      if: always()
      run: |
        docker stop keycloak || true
        docker rm keycloak || true